@userID = 13
@courseID = 22
@registrationID = 46

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiYWRtaW4iOnRydWUsImlhdCI6MTc1Mzg5NTgwNiwiZXhwIjoxNzUzODk5NDA2fQ.eUjL3oA1_CxURDzd4aL9hRHgJ79JQ1-CP3LlL416MWE
### Login to get JWT token
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "JakeTheDog",
  "password": "JakeAdmin123"
}

### User api requests
POST http://localhost:3001/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "Homie",
  "email": "homies@testing.com",
  "firstname": "Homie",
  "lastname": "Robertson",
  "telephone": "123-456-78910",
  "address": "123 Main",
  "admin": false,
  "aboutMe": "just testing stuff",
  "password": "dopePassword"
}
###

PUT http://localhost:3001/api/users/{{userID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "HomieWithACat",
  "email": "homie@testing.com",
  "firstname": "Max",
  "lastname": "Rodes",
  "telephone": "585-5858",
  "address": "456 Birch St.",
  "admin": false,
  "aboutMe": ""
}
###

DELETE http://localhost:3001/api/users/{{userID}}
Authorization: Bearer {{token}}
###

### Courses api requests
POST http://localhost:3001/api/courses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test Course",
  "description": "Testing",
  "credits": 2,
  "capacity": 20
}
###
PUT http://localhost:3001/api/courses/{{courseID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Course",
  "description": "Changed stuff",
  "credits": 3,
  "capacity": 25
}
###

DELETE http://localhost:3001/api/courses/{{courseID}}
Authorization: Bearer {{token}}
###

### Registration api requests

### Create a new registration
POST http://localhost:3001/api/registrations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": 1,
  "course_id": 20
}

###

### Update a registration
PUT http://localhost:3001/api/registrations/{{registrationID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": 1,
  "course_id": 2
}

###

### Delete a registration
DELETE http://localhost:3001/api/registrations/{{registrationID}}
Authorization: Bearer {{token}}

