### User api requests
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "James23",
  "email": "James@testmail.com",
  "firstname": "James",
  "lastname": "Smith",
  "telephone": "123-456-78910",
  "address": "123 Main",
  "admin": false
}
###

PUT http://localhost:3001/api/users/3
Content-Type: application/json

{
  "username": "TesterDon",
  "email": "tester2@testmail.com",
  "firstname": "Don",
  "lastname": "Tester",
  "telephone": "585-5858",
  "address": "456 Birch St.",
  "admin": true
}
###

DELETE http://localhost:3001/api/users/3
###

### Courses api requests
POST http://localhost:3001/api/courses
Content-Type: application/json

{
  "name": "Test Course",
  "description": "Testing",
  "credits": 2,
  "capacity": 20
}
###
PUT http://localhost:3001/api/courses/21
Content-Type: application/json

{
  "name": "Updated Course",
  "description": "Changed stuff",
  "credits": 3,
  "capacity": 25
}
###

DELETE http://localhost:3001/api/courses/21
###

### Registration api requests

### Create a new registration
POST http://localhost:3001/api/registrations
Content-Type: application/json

{
  "user_id": 2,
  "course_id": 15
}

###

### Update a registration
PUT http://localhost:3001/api/registrations/3
Content-Type: application/json

{
  "user_id": 2,
  "course_id": 2
}

###

### Delete a registration
DELETE http://localhost:3001/api/registrations/4

